version: "3"

services:
  postgres:
    image: postgres:14
    container_name: marquez_db
    environment:
      - POSTGRES_USER=marquez
      - POSTGRES_PASSWORD=marquez
      - POSTGRES_DB=marquez
    ports:
      - "5432:5432"
    volumes:
      - marquez_data:/var/lib/postgresql/data

  marquez-api:
    image: marquezproject/marquez:0.41.0
    container_name: marquez_api
    environment:
      - MARQUEZ_DB_USER=marquez
      - MARQUEZ_DB_PASSWORD=marquez
      - MARQUEZ_DB=marquez
      - MARQUEZ_DB_HOST=postgres
      - MARQUEZ_DB_PORT=5432
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - postgres
    restart: always

  marquez-web:
    image: marquezproject/marquez-web:0.41.0
    container_name: marquez_web
    environment:
      - MARQUEZ_HOST=marquez-api
      - MARQUEZ_PORT=5000
    ports:
      - "3002:3000"
    depends_on:
      - marquez-api
    restart: always

volumes:
  marquez_data:
